[2022-03-21 21:41:10,575] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: BQ_dag.external_task_sensor scheduled__2022-03-21T21:24:06.951066+00:00 [queued]>
[2022-03-21 21:41:10,582] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: BQ_dag.external_task_sensor scheduled__2022-03-21T21:24:06.951066+00:00 [queued]>
[2022-03-21 21:41:10,582] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 21:41:10,582] {taskinstance.py:1244} INFO - Starting attempt 4 of 6
[2022-03-21 21:41:10,582] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 21:41:10,590] {taskinstance.py:1264} INFO - Executing <Task(ExternalTaskSensor): external_task_sensor> on 2022-03-21 21:24:06.951066+00:00
[2022-03-21 21:41:10,594] {standard_task_runner.py:52} INFO - Started process 2531 to run task
[2022-03-21 21:41:10,597] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'BQ_dag', 'external_task_sensor', 'scheduled__2022-03-21T21:24:06.951066+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/extract_load_dags.py', '--cfg-path', '/tmp/tmpsroc1k5g', '--error-file', '/tmp/tmp_es4srnv']
[2022-03-21 21:41:10,597] {standard_task_runner.py:77} INFO - Job 39: Subtask external_task_sensor
[2022-03-21 21:41:10,715] {logging_mixin.py:109} INFO - Running <TaskInstance: BQ_dag.external_task_sensor scheduled__2022-03-21T21:24:06.951066+00:00 [running]> on host 7fae4c5ec6da
[2022-03-21 21:41:10,760] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BQ_dag
AIRFLOW_CTX_TASK_ID=external_task_sensor
AIRFLOW_CTX_EXECUTION_DATE=2022-03-21T21:24:06.951066+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-21T21:24:06.951066+00:00
[2022-03-21 21:41:10,761] {external_task.py:169} INFO - Poking for tasks None in dag EL_dag on 2022-03-21T21:24:06.951066+00:00 ... 
[2022-03-21 21:42:10,829] {external_task.py:169} INFO - Poking for tasks None in dag EL_dag on 2022-03-21T21:24:06.951066+00:00 ... 
[2022-03-21 21:43:10,899] {external_task.py:169} INFO - Poking for tasks None in dag EL_dag on 2022-03-21T21:24:06.951066+00:00 ... 
[2022-03-21 21:43:42,428] {local_task_job.py:211} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2022-03-21 21:43:42,429] {process_utils.py:120} INFO - Sending Signals.SIGTERM to group 2531. PIDs of all processes in the group: [2531]
[2022-03-21 21:43:42,429] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 2531
[2022-03-21 21:43:42,430] {taskinstance.py:1413} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-03-21 21:43:42,456] {process_utils.py:70} INFO - Process psutil.Process(pid=2531, status='terminated', exitcode=0, started='21:41:09') (2531) terminated with exit code 0
