[2022-03-18 22:39:56,426] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: EL_dag.extract_task scheduled__2019-03-01T00:00:00+00:00 [queued]>
[2022-03-18 22:39:56,432] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: EL_dag.extract_task scheduled__2019-03-01T00:00:00+00:00 [queued]>
[2022-03-18 22:39:56,432] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-18 22:39:56,432] {taskinstance.py:1244} INFO - Starting attempt 8 of 9
[2022-03-18 22:39:56,432] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-18 22:39:56,439] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): extract_task> on 2019-03-01 00:00:00+00:00
[2022-03-18 22:39:56,443] {standard_task_runner.py:52} INFO - Started process 369 to run task
[2022-03-18 22:39:56,445] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'EL_dag', 'extract_task', 'scheduled__2019-03-01T00:00:00+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/extract_load_dags.py', '--cfg-path', '/tmp/tmpq_155x9z', '--error-file', '/tmp/tmpsu96l3un']
[2022-03-18 22:39:56,446] {standard_task_runner.py:77} INFO - Job 54: Subtask extract_task
[2022-03-18 22:39:56,489] {logging_mixin.py:109} INFO - Running <TaskInstance: EL_dag.extract_task scheduled__2019-03-01T00:00:00+00:00 [running]> on host d6b2ec1ac43c
[2022-03-18 22:39:56,514] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.9/site-packages/airflow/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-03-18 22:39:56,533] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=EL_dag
AIRFLOW_CTX_TASK_ID=extract_task
AIRFLOW_CTX_EXECUTION_DATE=2019-03-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-03-01T00:00:00+00:00
[2022-03-18 22:39:56,534] {logging_mixin.py:109} INFO - 03 2019
[2022-03-18 22:39:59,943] {logging_mixin.py:109} INFO - the response is  200
[2022-03-18 22:39:59,943] {logging_mixin.py:109} INFO - here.........
[2022-03-18 22:39:59,981] {logging_mixin.py:109} INFO -    invoice_line_no                     date  ... sale_liters sale_gallons
0  INV-18353900011  2019-03-26T00:00:00.000  ...        0.30         0.07
1  INV-17917000018  2019-03-05T00:00:00.000  ...       36.00         9.51
2  INV-17945800021  2019-03-06T00:00:00.000  ...        9.00         2.37
3  INV-17922600002  2019-03-05T00:00:00.000  ...        9.00         2.37
4  INV-18364000013  2019-03-26T00:00:00.000  ...        6.00         1.58

[5 rows x 24 columns]
[2022-03-18 22:40:00,034] {logging_mixin.py:109} INFO - Data saved..........
[2022-03-18 22:40:00,035] {python.py:175} INFO - Done. Returned value was: None
[2022-03-18 22:40:00,048] {taskinstance.py:1272} INFO - Marking task as SUCCESS. dag_id=EL_dag, task_id=extract_task, execution_date=20190301T000000, start_date=20220318T223956, end_date=20220318T224000
[2022-03-18 22:40:00,075] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-18 22:40:00,102] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
